name: smart_shop_app
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.7
  google_nav_bar: ^5.0.7
  flutter_riverpod: ^2.5.3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  pigeon: ^22.6.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
